# Generated by Django 5.0.6 on 2025-08-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_failed',
            field=models.BooleanField(default=False, help_text='Indicates if email dispatch failed due to system errors'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='Indicates if verification email was successfully sent'),
        ),
    ]
