# Generated by Django 5.0.6 on 2024-07-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
