# Generated by Django 5.0.6 on 2025-08-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_email_failed_emailresendattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_reset_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Number of password reset attempts made'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_email_failed',
            field=models.BooleanField(default=False, help_text='Indicates if password reset email failed to send'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_email_sent',
            field=models.BooleanField(default=False, help_text='Indicates if password reset email was successfully sent'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when password reset email was last sent', null=True),
        ),
    ]
