# Generated by Django 5.0.6 on 2025-03-29 22:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('order_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Daily Sales',
                'verbose_name_plural': 'Daily Sales',
                'ordering': ['-date'],
            },
        ),
    ]
