# Generated by Django 5.0.6 on 2025-03-29 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apievent',
            options={'ordering': ['-timestamp'], 'verbose_name': 'API Event', 'verbose_name_plural': 'API Events'},
        ),
        migrations.AlterModelOptions(
            name='clickevent',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Click Event', 'verbose_name_plural': 'Click Events'},
        ),
        migrations.AlterModelOptions(
            name='errorlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Error Log', 'verbose_name_plural': 'Error Logs'},
        ),
        migrations.AlterModelOptions(
            name='formsubmission',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Form Submission', 'verbose_name_plural': 'Form Submissions'},
        ),
        migrations.AlterModelOptions(
            name='pageview',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Page View', 'verbose_name_plural': 'Page Views'},
        ),
        migrations.AlterModelOptions(
            name='searchquery',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Search Query', 'verbose_name_plural': 'Search Queries'},
        ),
        migrations.AlterModelOptions(
            name='useraccountdeactivation',
            options={'ordering': ['-deactivation_time'], 'verbose_name': 'User Account Deactivation', 'verbose_name_plural': 'User Account Deactivations'},
        ),
        migrations.AlterModelOptions(
            name='useraccountreactivation',
            options={'ordering': ['-reactivation_time'], 'verbose_name': 'User Account Reactivation', 'verbose_name_plural': 'User Account Reactivations'},
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['-timestamp'], 'verbose_name': 'User Activity', 'verbose_name_plural': 'User Activities'},
        ),
        migrations.AlterModelOptions(
            name='userbehavior',
            options={'ordering': ['-timestamp'], 'verbose_name': 'User Behavior', 'verbose_name_plural': 'User Behaviors'},
        ),
        migrations.AlterModelOptions(
            name='userengagement',
            options={'ordering': ['-timestamp'], 'verbose_name': 'User Engagement', 'verbose_name_plural': 'User Engagements'},
        ),
        migrations.AlterModelOptions(
            name='userfeedback',
            options={'ordering': ['-timestamp'], 'verbose_name': 'User Feedback', 'verbose_name_plural': 'User Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='userinteraction',
            options={'ordering': ['-timestamp'], 'verbose_name': 'User Interaction', 'verbose_name_plural': 'User Interactions'},
        ),
        migrations.AlterModelOptions(
            name='userlogin',
            options={'ordering': ['-login_time'], 'verbose_name': 'User Login', 'verbose_name_plural': 'User Logins'},
        ),
        migrations.AlterModelOptions(
            name='userlogout',
            options={'ordering': ['-logout_time'], 'verbose_name': 'User Logout', 'verbose_name_plural': 'User Logouts'},
        ),
        migrations.AlterModelOptions(
            name='usernotification',
            options={'ordering': ['-timestamp'], 'verbose_name': 'User Notification', 'verbose_name_plural': 'User Notifications'},
        ),
        migrations.AlterModelOptions(
            name='userpasswordchange',
            options={'ordering': ['-change_time'], 'verbose_name': 'User Password Change', 'verbose_name_plural': 'User Password Changes'},
        ),
        migrations.AlterModelOptions(
            name='userpasswordreset',
            options={'ordering': ['-reset_time'], 'verbose_name': 'User Password Reset', 'verbose_name_plural': 'User Password Resets'},
        ),
        migrations.AlterModelOptions(
            name='userpreference',
            options={'ordering': ['-timestamp'], 'verbose_name': 'User Preference', 'verbose_name_plural': 'User Preferences'},
        ),
        migrations.AlterModelOptions(
            name='userpreferencechange',
            options={'ordering': ['-timestamp'], 'verbose_name': 'User Preference Change', 'verbose_name_plural': 'User Preference Changes'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterModelOptions(
            name='userprofileupdate',
            options={'ordering': ['-update_time'], 'verbose_name': 'User Profile Update', 'verbose_name_plural': 'User Profile Updates'},
        ),
        migrations.AlterModelOptions(
            name='userregistration',
            options={'ordering': ['-registration_time'], 'verbose_name': 'User Registration', 'verbose_name_plural': 'User Registrations'},
        ),
        migrations.AlterModelOptions(
            name='usersession',
            options={'ordering': ['-start_time'], 'verbose_name': 'User Session', 'verbose_name_plural': 'User Sessions'},
        ),
    ]
