# Generated by Django 5.0.6 on 2025-08-18 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_apievent_options_alter_clickevent_options_and_more'),
        ('products', '0008_alter_product_options_product_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='activity_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CART_ADD', 'Add to Cart'), ('CART_REMOVE', 'Remove from Cart'), ('ORDER_PLACED', 'Order Placed'), ('PAYMENT', 'Payment Made'), ('PROFILE_UPDATE', 'Profile Updated'), ('ADDRESS_ADD', 'Address Added'), ('EMAIL_VERIFICATION', 'Email Verification'), ('REGISTRATION', 'Registration'), ('PASSWORD_CHANGE', 'Password Change'), ('PASSWORD_RESET', 'Password Reset'), ('PASSWORD_RESET_EMAIL_SENT', 'Password Reset Email Sent'), ('PASSWORD_RESET_EMAIL_FAILED', 'Password Reset Email Failed'), ('ACCOUNT_LOCKED', 'Account Locked'), ('SUSPICIOUS_ACTIVITY', 'Suspicious Activity')], max_length=50),
        ),
        migrations.CreateModel(
            name='SalesMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_visitors', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('cart_abandonment_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('new_customers', models.IntegerField(default=0)),
                ('returning_customers', models.IntegerField(default=0)),
                ('customer_acquisition_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Sales Metrics',
                'verbose_name_plural': 'Sales Metrics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'conversion_rate'], name='analytics_s_date_d7f2d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='CartAbandonmentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('cart_created', models.DateTimeField()),
                ('cart_abandoned', models.DateTimeField(auto_now_add=True)),
                ('cart_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('items_count', models.IntegerField()),
                ('abandonment_stage', models.CharField(max_length=50)),
                ('recovery_email_sent', models.BooleanField(default=False)),
                ('recovered', models.BooleanField(default=False)),
                ('recovery_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cart Abandonment Analytics',
                'verbose_name_plural': 'Cart Abandonment Analytics',
                'ordering': ['-cart_abandoned'],
                'indexes': [models.Index(fields=['user', 'cart_abandoned'], name='analytics_c_user_id_c4b5a8_idx'), models.Index(fields=['abandonment_stage', 'recovered'], name='analytics_c_abandon_d3bb2b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConversionFunnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('stage', models.CharField(choices=[('PRODUCT_VIEW', 'Product View'), ('CART_ADD', 'Add to Cart'), ('CHECKOUT_START', 'Checkout Started'), ('PAYMENT_INFO', 'Payment Info Added'), ('ORDER_COMPLETE', 'Order Completed')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversion Funnel',
                'verbose_name_plural': 'Conversion Funnels',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'session_id', 'timestamp'], name='analytics_c_user_id_58832c_idx'), models.Index(fields=['stage', 'timestamp'], name='analytics_c_stage_a8f3fb_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerLifetimeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('first_order_date', models.DateTimeField(blank=True, null=True)),
                ('last_order_date', models.DateTimeField(blank=True, null=True)),
                ('predicted_ltv', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customer_segment', models.CharField(default='new', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Lifetime Value',
                'verbose_name_plural': 'Customer Lifetime Values',
                'ordering': ['-total_spent'],
                'indexes': [models.Index(fields=['customer_segment', 'total_spent'], name='analytics_c_custome_9b87ee_idx'), models.Index(fields=['last_order_date'], name='analytics_c_last_or_c3071e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.IntegerField(default=0)),
                ('cart_additions', models.IntegerField(default=0)),
                ('purchases', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('conversion_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('cart_to_purchase_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Product Analytics',
                'verbose_name_plural': 'Product Analytics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['product', 'date'], name='analytics_p_product_01c7f1_idx'), models.Index(fields=['date', 'conversion_rate'], name='analytics_p_date_be393e_idx')],
                'unique_together': {('product', 'date')},
            },
        ),
    ]
