# Generated by Django 5.0.6 on 2025-08-18 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_useractivitylog_activity_type_salesmetrics_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apievent',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if the request failed', null=True),
        ),
        migrations.AddField(
            model_name='apievent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the client', null=True),
        ),
        migrations.AddField(
            model_name='apievent',
            name='referer',
            field=models.URLField(blank=True, help_text='Referer URL from the request headers', null=True),
        ),
        migrations.AddField(
            model_name='apievent',
            name='request_data',
            field=models.JSONField(blank=True, help_text='Request payload data (excluding sensitive information)', null=True),
        ),
        migrations.AddField(
            model_name='apievent',
            name='request_method',
            field=models.CharField(blank=True, choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('OPTIONS', 'OPTIONS'), ('HEAD', 'HEAD')], help_text='HTTP method used for the request', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='apievent',
            name='request_size',
            field=models.IntegerField(blank=True, help_text='Size of the request in bytes', null=True),
        ),
        migrations.AddField(
            model_name='apievent',
            name='response_size',
            field=models.IntegerField(blank=True, help_text='Size of the response in bytes', null=True),
        ),
        migrations.AddField(
            model_name='apievent',
            name='response_status_code',
            field=models.IntegerField(blank=True, help_text='HTTP response status code', null=True),
        ),
        migrations.AddField(
            model_name='apievent',
            name='session_id',
            field=models.CharField(blank=True, help_text='Session ID for tracking user sessions', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='apievent',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who made the API call', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apievent',
            name='user_agent',
            field=models.TextField(blank=True, help_text='User agent string from the request', null=True),
        ),
        migrations.AddIndex(
            model_name='apievent',
            index=models.Index(fields=['timestamp', 'status'], name='analytics_a_timesta_7abf32_idx'),
        ),
        migrations.AddIndex(
            model_name='apievent',
            index=models.Index(fields=['user', 'timestamp'], name='analytics_a_user_id_6b6638_idx'),
        ),
        migrations.AddIndex(
            model_name='apievent',
            index=models.Index(fields=['endpoint', 'status'], name='analytics_a_endpoin_b572d8_idx'),
        ),
        migrations.AddIndex(
            model_name='apievent',
            index=models.Index(fields=['ip_address', 'timestamp'], name='analytics_a_ip_addr_fba0d4_idx'),
        ),
    ]
