# Generated by Django 5.0.6 on 2025-08-22 16:24

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_apievent_error_message_apievent_ip_address_and_more'),
        ('categories', '0007_alter_category_options_category_display_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='searchanalytics',
            name='click_through_rate',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='searchanalytics',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchanalytics',
            name='search_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='searchanalytics',
            name='results_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='searchanalytics',
            unique_together={('query', 'date')},
        ),
        migrations.AddIndex(
            model_name='searchanalytics',
            index=models.Index(fields=['query', 'date'], name='analytics_s_query_2ac2f4_idx'),
        ),
        migrations.AddIndex(
            model_name='searchanalytics',
            index=models.Index(fields=['date', 'search_count'], name='analytics_s_date_c4f31f_idx'),
        ),
    ]
