# Generated by Django 5.0.6 on 2025-08-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_searchanalytics_click_through_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='activity_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CART_ADD', 'Add to Cart'), ('CART_REMOVE', 'Remove from Cart'), ('ORDER_PLACED', 'Order Placed'), ('PAYMENT', 'Payment Made'), ('PROFILE_UPDATE', 'Profile Updated'), ('ADDRESS_ADD', 'Address Added'), ('EMAIL_VERIFICATION', 'Email Verification'), ('REGISTRATION', 'Registration'), ('PASSWORD_CHANGE', 'Password Change'), ('PASSWORD_RESET', 'Password Reset'), ('PASSWORD_RESET_EMAIL_SENT', 'Password Reset Email Sent'), ('PASSWORD_RESET_EMAIL_FAILED', 'Password Reset Email Failed'), ('ACCOUNT_LOCKED', 'Account Locked'), ('SUSPICIOUS_ACTIVITY', 'Suspicious Activity'), ('SEARCH', 'Search Query')], max_length=50),
        ),
    ]
