# Generated by Django 5.0.6 on 2024-06-24 19:50

import categories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=categories.models.get_placeholder_image, upload_to='category_images/', validators=[categories.models.validate_image]),
        ),
    ]
