# Generated by Django 5.0.6 on 2024-09-14 11:19

import categories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='secondary_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='secondary_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/', validators=[categories.models.validate_image]),
        ),
    ]
