# Generated by Django 5.0.6 on 2025-08-18 11:02

import categories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_alter_category_options_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.PositiveIntegerField(blank=True, help_text='Display order for frontend (1-8). Leave blank for categories not shown in ordered list.', null=True, unique=True, validators=[categories.models.validate_display_order]),
        ),
    ]
