# Generated by Django 5.0.6 on 2025-08-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_alter_category_options_category_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Uncheck this box to deactivate the category.'),
        ),
    ]
