"""
Django settings for myecommerce project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
from datetime import timedelta
import sys
import tempfile



TIME_ZONE = 'Asia/Kolkata'
USE_TZ = True
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'django_debug.log'),
            'formatter': 'standard',
        },
        'console': {
            'level': 'ERROR',
            'class': 'logging.StreamHandler',
        },
    },
    'formatters': {
        'standard': {
            'format': '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = config('DEBUG', default=False, cast=bool)
DEBUG = True
ALLOWED_HOSTS = config('ALLOWED_HOSTS').split(',')

if DEBUG:
    # Development settings
    SECURE_SSL_REDIRECT = False
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
    CSP_IMG_SRC = ("'self'", 'data:', 'http://localhost:8000')
else:
    # Production settings
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Application definition

INSTALLED_APPS = [
    'jazzmin',   
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'taggit',
    'users',
    'categories',
    'products',
    'cart',
    'orders',
    'search',
    'shipping',
    'analytics',  # For API event logging (code provided below)
    'core',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'django_rest_passwordreset',
    'django.contrib.sites',
    'social_django',
    'corsheaders',
    'whitenoise.runserver_nostatic',
    'storages',
    'django_extensions',
    'import_export',
]

JAZZMIN_SETTINGS = {
    "site_title": "Gujju Admin",
    "site_header": "Gujju Admin",
    "site_brand": "Gujju Admin",
    "site_logo": None,  # Add this
    "welcome_sign": "Welcome to Gujju Admin",  # Add this
    "copyright": "CodeKarmaTech",  # Add this
    "search_model": ["users.CustomUser"],  # Updated to use only CustomUser
    
    # Existing settings
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],  # Add this
    "hide_models": [],  # Add this
    "order_with_respect_to": ["Users", "Products", "Orders", "Cart", "Analytics", "Shipping"],
    
    # Icons for models
    "icons": {  # Add this section
        "auth": "fas fa-users-cog",
        "users.CustomUser": "fas fa-user",
        "users.Address": "fas fa-address-card",
        "products.Product": "fas fa-box",
        "orders.Order": "fas fa-shopping-cart",
        "cart.Cart": "fas fa-shopping-basket",
        "analytics.APIEvent": "fas fa-chart-line"
    },
    
    # Update custom menu
    "custom_menu": [
        {
            "name": "Users",
            "icon": "fas fa-users",
            "models": ["users.CustomUser", "users.Address"],
            "url": "custom_admin:users_customuser_changelist"
        },
        # ... rest of your custom_menu items ...
    ],

    # Add these settings
    "show_ui_builder": True,
    "changeform_format": "horizontal_tabs",
    "related_modal_active": True,
    "custom_css": None,
    "custom_js": None,
    "show_apps": True,
    "show_filters": True
}

# Add this setting
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-success",
    "accent": "accent-teal",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-success",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),  # Short-lived access tokens
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # Reasonable period for refresh tokens
    'ROTATE_REFRESH_TOKENS': True,                   # Rotate refresh tokens upon each use
    'BLACKLIST_AFTER_ROTATION': True,                # Blacklist old tokens after rotation
    'ALGORITHM': 'HS256',                            # Standard signing algorithm
    'SIGNING_KEY': config('SECRET_KEY'),             # Use Django's secret key for signing JWTs
    'VERIFYING_KEY': None,                           # Typically the same as SIGNING_KEY unless using asymmetric keys
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'TOKEN_TYPE_CLAIM': 'token_type',
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '1000/day'
    },
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

AUTH_USER_MODEL = 'users.CustomUser' 

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'", 'https://apis.example.com', 'https://ajax.googleapis.com', "https://cdn.jsdelivr.net", "https://cdnjs.cloudflare.com")
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'", 'https://fonts.googleapis.com')
CSP_IMG_SRC = ("'self'", 'data:', 'https://api.gujjumasala.in', 'https://www.gujjumasala.in', "https:")
CSP_FONT_SRC = ("'self'", 'https://fonts.gstatic.com')
CSP_CONNECT_SRC = ("'self'", 'https://api.gujjumasala.in')


CSRF_TRUSTED_ORIGINS = [
    'https://gujjumasala.in',
    'https://www.gujjumasala.in',
    'https://api.gujjumasala.in',
]

# Allow all origins
CORS_ALLOW_ALL_ORIGINS = True  # Be cautious with this in production

# Or, allow specific origins
CORS_ALLOWED_ORIGINS = [
    'http://localhost:8000',  # Allow local development
    'https://www.gujjumasala.in',
    'http://43.204.235.86',
    'https://43.204.235.86:8000',
    'https://gujjumasala.in',
    'https://api.gujjumasala.in',
    # 'https://example.com',
]

# If you need to expose specific headers, you can use:
CORS_EXPOSE_HEADERS = ['Content-Type', 'X-CSRFToken']

ROOT_URLCONF = 'myecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request',
            ],
        },
    },
]
print("templates_base dir =", TEMPLATES)
WSGI_APPLICATION = 'myecommerce.wsgi.application'

SITE_ID = 1
# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DATABASE_NAME'),
        'USER': config('DATABASE_USER'),
        'PASSWORD': config('DATABASE_PASSWORD'),
        'HOST': config('DATABASE_HOST'),
        'PORT': config('DATABASE_PORT'),
        'TEST': {
            'NAME': 'test_myecommerce',
            'DEPENDENCIES': [],
            'SERIALIZE': False,
            'MIRROR': None,
        },
    }
}


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': config('DATABASE_NAME'),
#         'USER': config('DATABASE_USER'),
#         'PASSWORD': config('DATABASE_PASSWORD'),
#         'HOST': config('DATABASE_HOST'),
#         'PORT': config('DATABASE_PORT', default='5432'),
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# For tests
# MEDIA_ROOT = tempfile.mkdtemp()
# MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Add a flag to indicate testing mode
TESTING = 'test' in sys.argv
if 'test' in sys.argv or (len(sys.argv) > 1 and sys.argv[1] == 'test'):
    ENABLE_RATE_LIMIT = False
else:
    ENABLE_RATE_LIMIT = True

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = config('EMAIL_HOST', default='smtpout.secureserver.net')
# EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
# EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
# EMAIL_HOST_USER = config('EMAIL_HOST_USER')  # Your GoDaddy email
# EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')  # Your GoDaddy email password


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER')  # Your Gmail address
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')  # Your Gmail password


AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = config('GOOGLE_CLIENT_ID')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = config('GOOGLE_CLIENT_SECRET')


# # AWS S3 Settings
# AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
# AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
# AWS_STORAGE_BUCKET_NAME = 'media.gujjumasala.in'
# AWS_S3_REGION_NAME = 'ap-south-1'  # Replace with your region if different
# AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'

# # Media files configuration
# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
# MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'



# RAZORPAY_KEY_ID = config('RAZORPAY_KEY_ID')
# RAZORPAY_KEY_SECRET = config('RAZORPAY_KEY_SECRET')

# for Development use with default #

RAZORPAY_KEY_ID = config('RAZORPAY_KEY_ID', default='dummy_key')
RAZORPAY_KEY_SECRET = config('RAZORPAY_KEY_SECRET', default='dummy_secret')

SHIPROCKET_API_TOKEN = config('SHIPROCKET_API_TOKEN', default='dummy_token')
WAREHOUSE_PINCODE = "380009"
SHIPROCKET_BASE_URL = "https://apiv2.shiprocket.in/v1/external"

# Add admin site configuration
ADMIN_SITE_HEADER = "Gujju Admin"
ADMIN_SITE_TITLE = "Gujju Admin Portal"
ADMIN_INDEX_TITLE = "Welcome to Gujju Admin"