# Generated by Django 5.0.6 on 2024-06-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_weight',
        ),
        migrations.CreateModel(
            name='PriceWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('price', 'weight')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='price_weights',
            field=models.ManyToManyField(related_name='products', to='products.priceweight'),
        ),
    ]
