# Generated by Django 5.0.6 on 2024-06-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_price_weight_priceweight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_weights',
        ),
        migrations.AddField(
            model_name='product',
            name='price_weights',
            field=models.CharField(default='2000rs for 100gms', help_text="Enter price and weight in format '2000rs for 100gms'", max_length=100),
        ),
    ]
