# Generated by Django 5.0.6 on 2024-06-13 19:02

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_price_weights_product_price_weights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/', validators=[products.models.validate_image]),
        ),
    ]
