# Generated by Django 5.0.6 on 2025-08-28 10:34

import django.db.models.deletion
import products.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_options_product_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_file', models.FileField(help_text='Upload a ZIP file containing catalog data (max 100MB)', upload_to=products.models.bulk_upload_path, validators=[products.models.validate_zip_file])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('categories_created', models.PositiveIntegerField(default=0)),
                ('categories_updated', models.PositiveIntegerField(default=0)),
                ('products_created', models.PositiveIntegerField(default=0)),
                ('products_updated', models.PositiveIntegerField(default=0)),
                ('images_processed', models.PositiveIntegerField(default=0)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('processing_notes', models.TextField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Upload',
                'verbose_name_plural': 'Bulk Uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
