# Generated by Django 5.0.6 on 2025-08-28 20:07

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_bulkupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkupload',
            name='category_stats',
            field=models.JSONField(blank=True, default=dict, help_text='Category-wise statistics: {category_name: {expected: int, uploaded: int, errors: []}}'),
        ),
        migrations.AddField(
            model_name='bulkupload',
            name='detailed_errors',
            field=models.JSONField(blank=True, default=list, help_text='Detailed error information with expected vs given data'),
        ),
        migrations.AddField(
            model_name='bulkupload',
            name='empty_categories',
            field=models.JSONField(blank=True, default=list, help_text='List of category folders that were found empty'),
        ),
        migrations.AlterField(
            model_name='bulkupload',
            name='zip_file',
            field=models.FileField(help_text='Upload a ZIP file containing catalog data (max 400MB)', upload_to=products.models.bulk_upload_path, validators=[products.models.validate_zip_file]),
        ),
    ]
